/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Arrow;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hosam
 */
public class MainFrame extends javax.swing.JFrame implements Runnable {

    MoveController mc;

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        try {
            initComponents();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        drawingPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        startRotateBtn = new javax.swing.JButton();
        stopRotateBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        infoMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hosam Mukhairez (Line Rotator) - Intech");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(new java.awt.BorderLayout());

        drawingPanel.setBackground(new java.awt.Color(0, 0, 0));
        drawingPanel.setLayout(new java.awt.GridLayout());
        mainPanel.add(drawingPanel, java.awt.BorderLayout.CENTER);

        controlPanel.setLayout(new java.awt.GridLayout());

        startRotateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        startRotateBtn.setText("Start");
        startRotateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startRotateBtnActionPerformed(evt);
            }
        });
        controlPanel.add(startRotateBtn);

        stopRotateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stopRotateBtn.setText("Stop");
        stopRotateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopRotateBtnActionPerformed(evt);
            }
        });
        controlPanel.add(stopRotateBtn);

        mainPanel.add(controlPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 984, 583);

        fileMenu.setText("File");

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenu);

        jMenuBar1.add(fileMenu);

        infoMenu.setText("About");

        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        infoMenu.add(aboutMenu);

        jMenuBar1.add(infoMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(998, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startRotateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startRotateBtnActionPerformed
        // TODO add your handling code here:
        mc.startRotate();
    }//GEN-LAST:event_startRotateBtnActionPerformed

    private void stopRotateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopRotateBtnActionPerformed
        // TODO add your handling code here:
        mc.stopRotate();
    }//GEN-LAST:event_stopRotateBtnActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(this, "<html><p style=\"font-weight: bold;\">Hosam Mukhairez<br>Senior Software Developer</p><br><br>INTECH Creative Services Pvt. Ltd<br><br>Web :  https://theintechgroup.com/<br><br>E-Mail : amrita.pandit@ics-global.in<br><br>Tel  : +91-9687133057<br><br></html>", "Hosam Mukhairez (Line Rotator) - Intech", 1, new ImageIcon(System.getProperty("user.dir") + "\\image\\intech.png"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_aboutMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel drawingPanel;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu infoMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton startRotateBtn;
    private javax.swing.JButton stopRotateBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        mc = new MoveController();
        drawingPanel.add(mc, BorderLayout.CENTER);
        setVisible(true);
    }
}
